---
title: "Internship"
---

## Data Analyst Intern - Meituan Dianping Co., Ltd. 
<p>(July 2023 – August 2023)<p>
<p>·Developed **SQL dashboards** to monitor daily KPIs of over 400 sales personnel across 16 provinces, identifying key performance insights.<p>
<p>·Utilized **XGBoost machine learning models** in Python to forecast regional sales, enhancing predictive accuracy by adapting model hyperparameters.<p>
<p>·Designed performance metrics and incentive schemes that increased overall team KPIs by 25% through strategic data analyses and goal-setting.<p>

## Business Analyst Intern - JD.com, Inc. 
<p>(July 2022 – August 2022)<p>
<p>·Engineered a **logistic regression model** to streamline compliance by predicting store risk profiles, reducing processing times by 30%.<p>
<p>·Analyzed customer feedback using **NLP techniques** with Python, providing actionable insights into customer satisfaction and service quality.<p>

## Marketing & Analysis Intern - Beijing Huihuijia Technology Co., Ltd. 
<p>(July 2021 – September 2021)<p>
<p>·Enhanced social media engagement on TikTok, boosting follower growth by 20% through strategic content creation and optimization.<p>
<p>·Conducted detailed analyses of livestream performance, utilizing Excel to visualize sales trends and viewer engagement metrics.<p>

<style>
h2 {
    color: #0056b3; 
}
p {
    margin-left: 20px; 
}
</style>
